# Generated by Django 5.2.9 on 2026-04-09 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioRevisionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_id', models.CharField(max_length=128, unique=True)),
                ('reviser', models.CharField(max_length=128)),
                ('revision_comment', models.TextField(blank=True, null=True)),
                ('applied_changes', models.JSONField(default=dict)),
                ('revised_at', models.DateTimeField()),
                ('metadata', models.JSONField(default=dict)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='scenario_service.scenariorecord')),
            ],
            options={
                'ordering': ['revised_at', 'id'],
            },
        ),
    ]
