# Generated by Django 5.2.9 on 2026-04-10 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_service', '0002_scenariorevisionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioexecutionrecord',
            name='based_on_revision_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='scenarioexecutionrecord',
            name='based_on_suggestion_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='scenarioexecutionrecord',
            name='change_summary',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='scenarioexecutionrecord',
            name='diff_summary',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='scenarioexecutionrecord',
            name='trigger_source',
            field=models.CharField(default='manual', max_length=32),
        ),
        migrations.CreateModel(
            name='ScenarioSourceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(default='scenario', max_length=32)),
                ('entity_id', models.CharField(blank=True, default='', max_length=128)),
                ('source_type', models.CharField(max_length=32)),
                ('source_ref', models.CharField(max_length=255)),
                ('confidence', models.CharField(default='high', max_length=16)),
                ('issue_tags', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='scenario_service.scenariorecord')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
