# Generated by Django 5.2.9 on 2026-04-10 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_service', '0003_scenarioexecutionrecord_based_on_revision_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioSuggestionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_id', models.CharField(max_length=128, unique=True)),
                ('suggestion_type', models.CharField(max_length=64)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.CharField(blank=True, default='', max_length=128)),
                ('baseline_revision_id', models.CharField(blank=True, default='', max_length=128)),
                ('patch_payload', models.JSONField(default=dict)),
                ('diff_summary', models.JSONField(default=dict)),
                ('confidence', models.CharField(default='medium', max_length=16)),
                ('apply_status', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='scenario_service.scenariorecord')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
