# Generated by Django 5.2.9 on 2026-04-14 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_service', '0004_scenariosuggestionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineVersionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_version_id', models.CharField(max_length=128, unique=True)),
                ('version_code', models.CharField(max_length=128)),
                ('version_name', models.CharField(max_length=255)),
                ('is_frozen', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scenario_set__scenario_set_code', '-is_active', 'version_code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GovernanceMigrationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration_id', models.CharField(max_length=128, unique=True)),
                ('migration_name', models.CharField(max_length=128)),
                ('migration_scope', models.CharField(default='default_project_bootstrap', max_length=64)),
                ('status', models.CharField(default='completed', max_length=32)),
                ('migrated_scenario_count', models.PositiveIntegerField(default=0)),
                ('migrated_execution_count', models.PositiveIntegerField(default=0)),
                ('failed_entity_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-executed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=128, unique=True)),
                ('project_code', models.CharField(max_length=128, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('lifecycle_status', models.CharField(default='active', max_length=32)),
                ('is_archived', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['project_code', 'id'],
            },
        ),
        migrations.AddField(
            model_name='scenarioexecutionrecord',
            name='workspace_root',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scenarioexecutionrecord',
            name='baseline_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='scenario_service.baselineversionrecord'),
        ),
        migrations.AddField(
            model_name='scenarioexecutionrecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='scenario_service.projectrecord'),
        ),
        migrations.AddField(
            model_name='scenariorecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scenarios', to='scenario_service.projectrecord'),
        ),
        migrations.CreateModel(
            name='ScenarioSetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_set_id', models.CharField(max_length=128, unique=True)),
                ('scenario_set_code', models.CharField(max_length=128)),
                ('scenario_set_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(default=list)),
                ('is_archived', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_sets', to='scenario_service.projectrecord')),
            ],
            options={
                'ordering': ['project__project_code', 'scenario_set_code', 'id'],
            },
        ),
        migrations.AddField(
            model_name='baselineversionrecord',
            name='scenario_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_versions', to='scenario_service.scenariosetrecord'),
        ),
        migrations.AddField(
            model_name='scenarioexecutionrecord',
            name='scenario_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='scenario_service.scenariosetrecord'),
        ),
        migrations.AddField(
            model_name='scenariorecord',
            name='scenario_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scenarios', to='scenario_service.scenariosetrecord'),
        ),
        migrations.CreateModel(
            name='TestEnvironmentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_id', models.CharField(max_length=128, unique=True)),
                ('environment_code', models.CharField(max_length=128)),
                ('environment_name', models.CharField(max_length=255)),
                ('base_url', models.CharField(blank=True, default='', max_length=255)),
                ('auth_config', models.JSONField(default=dict)),
                ('request_headers', models.JSONField(default=dict)),
                ('variable_set', models.JSONField(default=dict)),
                ('proxy_config', models.JSONField(default=dict)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('isolation_key', models.CharField(blank=True, default='', max_length=128)),
                ('is_default', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='scenario_service.projectrecord')),
            ],
            options={
                'ordering': ['project__project_code', 'environment_code', 'id'],
            },
        ),
        migrations.AddField(
            model_name='scenarioexecutionrecord',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='scenario_service.testenvironmentrecord'),
        ),
        migrations.AddField(
            model_name='scenariorecord',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scenarios', to='scenario_service.testenvironmentrecord'),
        ),
        migrations.AddConstraint(
            model_name='scenariosetrecord',
            constraint=models.UniqueConstraint(fields=('project', 'scenario_set_code'), name='uniq_project_scenario_set_code'),
        ),
        migrations.AddConstraint(
            model_name='baselineversionrecord',
            constraint=models.UniqueConstraint(fields=('scenario_set', 'version_code'), name='uniq_scenario_set_baseline_version_code'),
        ),
        migrations.AddConstraint(
            model_name='testenvironmentrecord',
            constraint=models.UniqueConstraint(fields=('project', 'environment_code'), name='uniq_project_environment_code'),
        ),
    ]
