# Generated by Django 5.2.9 on 2026-04-15 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_service', '0005_baselineversionrecord_governancemigrationrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioAuditLogRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_id', models.CharField(max_length=128, unique=True)),
                ('actor_name', models.CharField(max_length=128)),
                ('action_type', models.CharField(max_length=64)),
                ('action_result', models.CharField(max_length=32)),
                ('target_type', models.CharField(default='scenario', max_length=32)),
                ('target_id', models.CharField(blank=True, default='', max_length=128)),
                ('detail_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='scenario_service.scenarioexecutionrecord')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='scenario_service.projectrecord')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='scenario_service.scenariorecord')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRoleAssignmentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=128, unique=True)),
                ('subject_name', models.CharField(max_length=128)),
                ('role_code', models.CharField(max_length=32)),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_execute', models.BooleanField(default=False)),
                ('can_review', models.BooleanField(default=False)),
                ('can_schedule', models.BooleanField(default=False)),
                ('can_grant', models.BooleanField(default=False)),
                ('granted_by', models.CharField(default='system', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='scenario_service.projectrecord')),
            ],
            options={
                'ordering': ['project__project_code', 'subject_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'subject_name'), name='uniq_project_role_assignment_subject')],
            },
        ),
    ]
