# Generated by Django 5.2.9 on 2026-04-15 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenario_service", "0006_scenarioauditlogrecord_projectroleassignmentrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrafficCaptureFormalizationRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("confirmation_id", models.CharField(max_length=128, unique=True)),
                ("confirmation_status", models.CharField(default="draft", max_length=32)),
                ("binding_status", models.CharField(default="pending", max_length=32)),
                ("execution_readiness", models.CharField(default="blocked", max_length=32)),
                ("confirmed_by", models.CharField(blank=True, default="", max_length=128)),
                ("bindings_confirmed_by", models.CharField(blank=True, default="", max_length=128)),
                ("last_execution_id", models.CharField(blank=True, default="", max_length=128)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="traffic_capture_formalizations",
                        to="scenario_service.testenvironmentrecord",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="traffic_capture_formalizations",
                        to="scenario_service.projectrecord",
                    ),
                ),
                (
                    "scenario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic_capture_formalization",
                        to="scenario_service.scenariorecord",
                    ),
                ),
            ],
            options={
                "ordering": ["project__project_code", "scenario__scenario_code", "id"],
            },
        ),
    ]
