# Generated by Django 5.2.9 on 2026-04-15 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_service', '0007_trafficcaptureformalizationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioScheduleBatchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_batch_id', models.CharField(max_length=128, unique=True)),
                ('created_by', models.CharField(max_length=128)),
                ('queue_status', models.CharField(default='queued', max_length=32)),
                ('dispatch_strategy', models.CharField(default='immediate', max_length=32)),
                ('trigger_source', models.CharField(default='schedule_batch', max_length=32)),
                ('workspace_root', models.CharField(blank=True, default='', max_length=255)),
                ('aggregate_summary', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baseline_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_batches', to='scenario_service.baselineversionrecord')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_batches', to='scenario_service.testenvironmentrecord')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_batches', to='scenario_service.projectrecord')),
                ('scenario_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_batches', to='scenario_service.scenariosetrecord')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioScheduleItemRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_item_id', models.CharField(max_length=128, unique=True)),
                ('item_order', models.PositiveIntegerField(default=1)),
                ('item_status', models.CharField(default='queued', max_length=32)),
                ('retry_policy', models.JSONField(default=dict)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retry_count', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('canceled_reason', models.TextField(blank=True, default='')),
                ('latest_result_summary', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='scenario_service.scenarioexecutionrecord')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_items', to='scenario_service.scenariorecord')),
                ('schedule_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scenario_service.scenarioschedulebatchrecord')),
            ],
            options={
                'ordering': ['item_order', 'id'],
            },
        ),
    ]
