# Generated by Django 5.2.9 on 2026-04-16 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenario_service", "0008_scenarioschedulebatchrecord_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiGovernancePolicyRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("policy_id", models.CharField(max_length=128, unique=True)),
                ("scope_type", models.CharField(default="project", max_length=32)),
                ("scope_ref", models.CharField(blank=True, default="", max_length=128)),
                ("suggestion_types", models.JSONField(default=list)),
                ("approval_mode", models.CharField(default="manual_review", max_length=32)),
                ("rollback_mode", models.CharField(default="snapshot_restore", max_length=32)),
                ("auto_execution_enabled", models.BooleanField(default=False)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_governance_policies",
                        to="scenario_service.projectrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["project__project_code", "scope_type", "scope_ref", "id"],
            },
        ),
        migrations.CreateModel(
            name="AiSuggestionDecisionRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("decision_id", models.CharField(max_length=128, unique=True)),
                ("decision_type", models.CharField(max_length=32)),
                ("decision_status", models.CharField(default="completed", max_length=32)),
                ("actor_name", models.CharField(max_length=128)),
                ("decision_comment", models.TextField(blank=True, default="")),
                ("snapshot_before", models.JSONField(default=dict)),
                ("snapshot_after", models.JSONField(default=dict)),
                ("related_revision_id", models.CharField(blank=True, default="", max_length=128)),
                ("related_execution_id", models.CharField(blank=True, default="", max_length=128)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ai_suggestion_decisions",
                        to="scenario_service.projectrecord",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_suggestion_decisions",
                        to="scenario_service.scenariorecord",
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_records",
                        to="scenario_service.scenariosuggestionrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="aigovernancepolicyrecord",
            constraint=models.UniqueConstraint(
                fields=("project", "scope_type", "scope_ref"),
                name="uniq_project_ai_governance_scope",
            ),
        ),
    ]
