# Generated by Django 5.2.9 on 2026-04-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_service', '0009_aigovernancepolicyrecord_aisuggestiondecisionrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePreferenceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_code', models.CharField(default='dark', max_length=32)),
                ('applied_by', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
