# Generated by Django 5.2.9 on 2026-04-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_service', '0010_add_theme_preference_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureProxyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_session_id', models.CharField(max_length=128, unique=True)),
                ('project_code', models.CharField(max_length=128)),
                ('module_code', models.CharField(max_length=128)),
                ('submodule_code', models.CharField(max_length=128)),
                ('operator', models.CharField(max_length=128)),
                ('listen_port', models.PositiveIntegerField()),
                ('filter_url_prefix', models.CharField(blank=True, default='', max_length=255)),
                ('filter_ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(default='running', max_length=32)),
                ('metadata', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
