# Generated by Django 5.2.9 on 2026-04-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_service', '0011_add_capture_proxy_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJobRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_job_id', models.CharField(max_length=128, unique=True)),
                ('project_code', models.CharField(max_length=128)),
                ('model_code', models.CharField(max_length=128)),
                ('case_code', models.CharField(max_length=128)),
                ('pytest_exit_code', models.IntegerField(default=-1)),
                ('pytest_status', models.CharField(default='pending', max_length=32)),
                ('submission_status', models.CharField(default='pending', max_length=32)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
